### ISSUE TITLE
ISL is not working on any repo (Windows)

### ISSUE THREAD

**Issue by watk** [tnesbitt210/interactive-smartlog-issues#3]
I've tried using ISL on a couple of repos but it sits there spinning indefinitely:
![image](https://github.com/tnesbitt210/interactive-smartlog-issues/assets/7245795/73026639-f22c-49f9-9d03-59923e484010)

**Comment by watk** [comment]
Is there any info I can gather?

**Comment by tnesbitt210** [comment]
Hey @watk , thanks for the flag on this - I haven't seen this before but it's definitely going to be on my priority list to fix. FWIW, I've been developing this on a mac & haven't dogfood-ed on windows.

I can try to add some logs in the next week or so, so that we can inspect via the output logger you've screen-shotted. Will re-comment here when I do that.

FYI - when ISL first starts, it runs a bunch of git commands to gather data to populate the UI. The spinner you're seeing is what shows during that time.

If you have any updates, let me know! Sounds like it's not repo-specific, but lmk if you find evidence to the contrary.

**Comment by tnesbitt210** [comment]
@watk , this issue should be fixed now as of version 0.0.42. Debugged it by installing a VM on my mac.

In case you're curious, I was using hash^1 to refer to a commit's parent, but that doesn't work in windows. So I switched it to hash~1

Also squashed a couple of other windows-specific bugs while I was over there. Please let me know if you find anything else, as the windows flow gets pretty much no testing from me.

Thanks again, let me know if you're still blocked by anything, and enjoy ISL!

**Comment by watk** [comment]
Nice, thanks!
